services:
  db:
    container_name: zabbix-postgres
    image: postgres:16.3
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
    volumes:
      - ./postgresql:/var/lib/postgresql:rw

  server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ubuntu-trunk
    depends_on:
      - db
    init: true
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix

  web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-trunk
    init: true
    depends_on:
      - server
    ports:
      - 8080:8080
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix

  